# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nación Lumpen
email: nacion-lumpen@googlegroups.com
description: >
  Nación Lumpen, la lista de correo de unos inquietos programadores a los que
  les gusta hacer cosas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nacionlumpen.com"
twitter_username: nacionlumpen
github_username:  nacionlumpen

# Build settings
markdown: kramdown
